basePath: /
definitions:
  api.ChangePasswordInput:
    properties:
      email:
        type: string
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  api.EmailExistResponse:
    properties:
      code:
        type: integer
      email:
        type: string
      isExist:
        type: boolean
      msg:
        type: string
    type: object
  api.EmailInput:
    properties:
      email:
        type: string
    type: object
  api.EmailPassword:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.ForgotPasswordInput:
    properties:
      email:
        type: string
    type: object
  api.StatusInfoResponse:
    properties:
      code:
        type: integer
      msg:
        type: string
      status:
        type: boolean
    type: object
  database.TeacherProfile:
    properties:
      achievements:
        type: string
      created_at:
        type: string
      experience_years:
        type: integer
      first_name:
        type: string
      interests:
        type: string
      last_name:
        type: string
      past_experiences:
        type: string
      qualifications:
        type: string
      skills:
        type: string
      specialization:
        type: string
      teacher_id:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  database.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      password_hash:
        type: string
      role:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      username:
        type: string
    type: object
  model.CreateUser:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
host: 0.0.0.0:8080
info:
  contact:
    email: support@swagger.io
    name: API Support (Ashwani)
    url: http://www.swagger.io/support
  description: These are APIs for Class, Subject and Teacher Management.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API for Class Management
  version: "1.0"
paths:
  /changePassword:
    post:
      description: To Change Password by existing user
      parameters:
      - description: It takes json as input
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/api.ChangePasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.StatusInfoResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Change Password of the user
      tags:
      - User Module
  /createTeacherProfile:
    post:
      consumes:
      - application/json
      description: To Create Teacher Profile
      parameters:
      - description: It takes json as input
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/database.TeacherProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.TeacherProfile'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create Teacher Profile
      tags:
      - Teacher
  /forgotPassword:
    post:
      consumes:
      - application/json
      description: To retrieve the password
      parameters:
      - description: It takes json as input
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/api.ForgotPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Forgot Password
      tags:
      - User Module
  /getTeacherProfile/{user_id}:
    post:
      consumes:
      - application/json
      description: To Retrieve Teacher Profile
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.TeacherProfile'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Retrieve Teacher Profile
      tags:
      - Teacher
  /isUserExist:
    post:
      description: To check if user exists or not
      parameters:
      - description: It takes email as input
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/api.EmailInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.EmailExistResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: To check whether Email already registered with any User or not.
      tags:
      - User Module
  /signIn:
    post:
      description: To login by existing user
      parameters:
      - description: It takes json as input
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/api.EmailPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign In user
      tags:
      - User Module
  /signUp:
    post:
      description: To create a new user
      parameters:
      - description: It takes json as input
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/model.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CreateUser'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Sign Up by User
      tags:
      - User Module
schemes:
- http
swagger: "2.0"
